/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api/verify-payment'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiUpdateOrderRouteImport } from './routes/api/update-order'
import { Route as ApiSendShippedEmailRouteImport } from './routes/api/send-shipped-email'
import { Route as ApiSendOtpRouteImport } from './routes/api/send-otp'
import { Route as ApiSendConfirmationRouteImport } from './routes/api/send-confirmation'
import { Route as ApiSaveOrderRouteImport } from './routes/api/save-order'
import { Route as ApiResolveMapsUrlRouteImport } from './routes/api/resolve-maps-url'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiNotifyAdminRouteImport } from './routes/api/notify-admin'
import { Route as ApiGetOrderRouteImport } from './routes/api/get-order'
import { Route as ApiDiagRouteImport } from './routes/api/diag'
import { Route as ApiCreateOrderRouteImport } from './routes/api/create-order'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiAdminPasswordRouteImport } from './routes/api/admin-password'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as ApiNewsletterSubscribeRouteImport } from './routes/api/newsletter/subscribe'
import { Route as AdminProductNewRouteImport } from './routes/admin.product.new'
import { Route as AdminProductIdRouteImport } from './routes/admin.product.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateOrderRoute = ApiUpdateOrderRouteImport.update({
  id: '/api/update-order',
  path: '/api/update-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendShippedEmailRoute = ApiSendShippedEmailRouteImport.update({
  id: '/api/send-shipped-email',
  path: '/api/send-shipped-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendOtpRoute = ApiSendOtpRouteImport.update({
  id: '/api/send-otp',
  path: '/api/send-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendConfirmationRoute = ApiSendConfirmationRouteImport.update({
  id: '/api/send-confirmation',
  path: '/api/send-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveOrderRoute = ApiSaveOrderRouteImport.update({
  id: '/api/save-order',
  path: '/api/save-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResolveMapsUrlRoute = ApiResolveMapsUrlRouteImport.update({
  id: '/api/resolve-maps-url',
  path: '/api/resolve-maps-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyAdminRoute = ApiNotifyAdminRouteImport.update({
  id: '/api/notify-admin',
  path: '/api/notify-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetOrderRoute = ApiGetOrderRouteImport.update({
  id: '/api/get-order',
  path: '/api/get-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagRoute = ApiDiagRouteImport.update({
  id: '/api/diag',
  path: '/api/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateOrderRoute = ApiCreateOrderRouteImport.update({
  id: '/api/create-order',
  path: '/api/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPasswordRoute = ApiAdminPasswordRouteImport.update({
  id: '/api/admin-password',
  path: '/api/admin-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const ApiNewsletterSubscribeRoute = ApiNewsletterSubscribeRouteImport.update({
  id: '/api/newsletter/subscribe',
  path: '/api/newsletter/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductNewRoute = AdminProductNewRouteImport.update({
  id: '/product/new',
  path: '/product/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductIdRoute = AdminProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/my-orders': typeof MyOrdersRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/admin-password': typeof ApiAdminPasswordRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/diag': typeof ApiDiagRoute
  '/api/get-order': typeof ApiGetOrderRoute
  '/api/notify-admin': typeof ApiNotifyAdminRoute
  '/api/products': typeof ApiProductsRoute
  '/api/resolve-maps-url': typeof ApiResolveMapsUrlRoute
  '/api/save-order': typeof ApiSaveOrderRoute
  '/api/send-confirmation': typeof ApiSendConfirmationRoute
  '/api/send-otp': typeof ApiSendOtpRoute
  '/api/send-shipped-email': typeof ApiSendShippedEmailRoute
  '/api/update-order': typeof ApiUpdateOrderRoute
  '/api/users': typeof ApiUsersRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/admin/product/new': typeof AdminProductNewRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/my-orders': typeof MyOrdersRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/admin-password': typeof ApiAdminPasswordRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/diag': typeof ApiDiagRoute
  '/api/get-order': typeof ApiGetOrderRoute
  '/api/notify-admin': typeof ApiNotifyAdminRoute
  '/api/products': typeof ApiProductsRoute
  '/api/resolve-maps-url': typeof ApiResolveMapsUrlRoute
  '/api/save-order': typeof ApiSaveOrderRoute
  '/api/send-confirmation': typeof ApiSendConfirmationRoute
  '/api/send-otp': typeof ApiSendOtpRoute
  '/api/send-shipped-email': typeof ApiSendShippedEmailRoute
  '/api/update-order': typeof ApiUpdateOrderRoute
  '/api/users': typeof ApiUsersRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/admin/product/new': typeof AdminProductNewRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/my-orders': typeof MyOrdersRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/admin-password': typeof ApiAdminPasswordRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/diag': typeof ApiDiagRoute
  '/api/get-order': typeof ApiGetOrderRoute
  '/api/notify-admin': typeof ApiNotifyAdminRoute
  '/api/products': typeof ApiProductsRoute
  '/api/resolve-maps-url': typeof ApiResolveMapsUrlRoute
  '/api/save-order': typeof ApiSaveOrderRoute
  '/api/send-confirmation': typeof ApiSendConfirmationRoute
  '/api/send-otp': typeof ApiSendOtpRoute
  '/api/send-shipped-email': typeof ApiSendShippedEmailRoute
  '/api/update-order': typeof ApiUpdateOrderRoute
  '/api/users': typeof ApiUsersRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/admin/product/new': typeof AdminProductNewRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/login'
    | '/my-orders'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/hero'
    | '/admin/orders'
    | '/admin/settings'
    | '/api/admin-password'
    | '/api/categories'
    | '/api/create-order'
    | '/api/diag'
    | '/api/get-order'
    | '/api/notify-admin'
    | '/api/products'
    | '/api/resolve-maps-url'
    | '/api/save-order'
    | '/api/send-confirmation'
    | '/api/send-otp'
    | '/api/send-shipped-email'
    | '/api/update-order'
    | '/api/users'
    | '/api/verify-payment'
    | '/product/$id'
    | '/admin/'
    | '/admin/product/$id'
    | '/admin/product/new'
    | '/api/newsletter/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/login'
    | '/my-orders'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/hero'
    | '/admin/orders'
    | '/admin/settings'
    | '/api/admin-password'
    | '/api/categories'
    | '/api/create-order'
    | '/api/diag'
    | '/api/get-order'
    | '/api/notify-admin'
    | '/api/products'
    | '/api/resolve-maps-url'
    | '/api/save-order'
    | '/api/send-confirmation'
    | '/api/send-otp'
    | '/api/send-shipped-email'
    | '/api/update-order'
    | '/api/users'
    | '/api/verify-payment'
    | '/product/$id'
    | '/admin'
    | '/admin/product/$id'
    | '/admin/product/new'
    | '/api/newsletter/subscribe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/login'
    | '/my-orders'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/hero'
    | '/admin/orders'
    | '/admin/settings'
    | '/api/admin-password'
    | '/api/categories'
    | '/api/create-order'
    | '/api/diag'
    | '/api/get-order'
    | '/api/notify-admin'
    | '/api/products'
    | '/api/resolve-maps-url'
    | '/api/save-order'
    | '/api/send-confirmation'
    | '/api/send-otp'
    | '/api/send-shipped-email'
    | '/api/update-order'
    | '/api/users'
    | '/api/verify-payment'
    | '/product/$id'
    | '/admin/'
    | '/admin/product/$id'
    | '/admin/product/new'
    | '/api/newsletter/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  MyOrdersRoute: typeof MyOrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  ApiAdminPasswordRoute: typeof ApiAdminPasswordRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiCreateOrderRoute: typeof ApiCreateOrderRoute
  ApiDiagRoute: typeof ApiDiagRoute
  ApiGetOrderRoute: typeof ApiGetOrderRoute
  ApiNotifyAdminRoute: typeof ApiNotifyAdminRoute
  ApiProductsRoute: typeof ApiProductsRoute
  ApiResolveMapsUrlRoute: typeof ApiResolveMapsUrlRoute
  ApiSaveOrderRoute: typeof ApiSaveOrderRoute
  ApiSendConfirmationRoute: typeof ApiSendConfirmationRoute
  ApiSendOtpRoute: typeof ApiSendOtpRoute
  ApiSendShippedEmailRoute: typeof ApiSendShippedEmailRoute
  ApiUpdateOrderRoute: typeof ApiUpdateOrderRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiNewsletterSubscribeRoute: typeof ApiNewsletterSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-order': {
      id: '/api/update-order'
      path: '/api/update-order'
      fullPath: '/api/update-order'
      preLoaderRoute: typeof ApiUpdateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-shipped-email': {
      id: '/api/send-shipped-email'
      path: '/api/send-shipped-email'
      fullPath: '/api/send-shipped-email'
      preLoaderRoute: typeof ApiSendShippedEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-otp': {
      id: '/api/send-otp'
      path: '/api/send-otp'
      fullPath: '/api/send-otp'
      preLoaderRoute: typeof ApiSendOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-confirmation': {
      id: '/api/send-confirmation'
      path: '/api/send-confirmation'
      fullPath: '/api/send-confirmation'
      preLoaderRoute: typeof ApiSendConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-order': {
      id: '/api/save-order'
      path: '/api/save-order'
      fullPath: '/api/save-order'
      preLoaderRoute: typeof ApiSaveOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resolve-maps-url': {
      id: '/api/resolve-maps-url'
      path: '/api/resolve-maps-url'
      fullPath: '/api/resolve-maps-url'
      preLoaderRoute: typeof ApiResolveMapsUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-admin': {
      id: '/api/notify-admin'
      path: '/api/notify-admin'
      fullPath: '/api/notify-admin'
      preLoaderRoute: typeof ApiNotifyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-order': {
      id: '/api/get-order'
      path: '/api/get-order'
      fullPath: '/api/get-order'
      preLoaderRoute: typeof ApiGetOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diag': {
      id: '/api/diag'
      path: '/api/diag'
      fullPath: '/api/diag'
      preLoaderRoute: typeof ApiDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-order': {
      id: '/api/create-order'
      path: '/api/create-order'
      fullPath: '/api/create-order'
      preLoaderRoute: typeof ApiCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-password': {
      id: '/api/admin-password'
      path: '/api/admin-password'
      fullPath: '/api/admin-password'
      preLoaderRoute: typeof ApiAdminPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/newsletter/subscribe': {
      id: '/api/newsletter/subscribe'
      path: '/api/newsletter/subscribe'
      fullPath: '/api/newsletter/subscribe'
      preLoaderRoute: typeof ApiNewsletterSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/product/new': {
      id: '/admin/product/new'
      path: '/product/new'
      fullPath: '/admin/product/new'
      preLoaderRoute: typeof AdminProductNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product/$id': {
      id: '/admin/product/$id'
      path: '/product/$id'
      fullPath: '/admin/product/$id'
      preLoaderRoute: typeof AdminProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductIdRoute: typeof AdminProductIdRoute
  AdminProductNewRoute: typeof AdminProductNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductIdRoute: AdminProductIdRoute,
  AdminProductNewRoute: AdminProductNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  MyOrdersRoute: MyOrdersRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  ApiAdminPasswordRoute: ApiAdminPasswordRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiCreateOrderRoute: ApiCreateOrderRoute,
  ApiDiagRoute: ApiDiagRoute,
  ApiGetOrderRoute: ApiGetOrderRoute,
  ApiNotifyAdminRoute: ApiNotifyAdminRoute,
  ApiProductsRoute: ApiProductsRoute,
  ApiResolveMapsUrlRoute: ApiResolveMapsUrlRoute,
  ApiSaveOrderRoute: ApiSaveOrderRoute,
  ApiSendConfirmationRoute: ApiSendConfirmationRoute,
  ApiSendOtpRoute: ApiSendOtpRoute,
  ApiSendShippedEmailRoute: ApiSendShippedEmailRoute,
  ApiUpdateOrderRoute: ApiUpdateOrderRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
  ProductIdRoute: ProductIdRoute,
  ApiNewsletterSubscribeRoute: ApiNewsletterSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
